#
# This file might sound important but...
# It is only used by the hosting on GitHub Pages, it has no other importance to the project
#

title: "KubeView"
# remote_theme: benc-uk/theme-msdark
favicon: /web/client/src/assets/logo.png
buttons:
  - b0:
    text: Main Docs
    href: /kubeview/
  - b1:
    text: Server
    href: /kubeview/cmd/server
  - b2:
    text: Frontend
    href: /kubeview/web/client
  - b3:
    text: Helm
    href: /kubeview/charts
